name: tapit
description: Tapit is a challenging mobile game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Design
  google_fonts: ^6.0.0
  auto_size_text: ^3.0.0
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  confetti: ^0.7.0
  material_design_icons_flutter: 7.0.7296
  flutter_animate: ^4.3.0
  another_flushbar: ^1.12.30

  # State management
  flutter_riverpod: ^2.4.0

  # Online
  socket_io_client: ^2.0.2

  # Utils
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1

  # Sound
  audioplayers: ^5.2.1

  # Localization
  easy_localization: ^3.0.3

  # Ads
  google_mobile_ads: ^3.1.0

  # Firebase
  firebase_core: ^2.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/circular_std/black.ttf
          weight: 900
        - asset: assets/fonts/circular_std/bold.ttf
          weight: 700
        - asset: assets/fonts/circular_std/book.ttf
          weight: 400
        - asset: assets/fonts/circular_std/medium.ttf
          weight: 500
  assets:
    - assets/lotties/

    - assets/svgs/buttons/online/
    - assets/svgs/buttons/online/en/
    - assets/svgs/buttons/online/it/

    - assets/svgs/buttons/menu/en/
    - assets/svgs/buttons/menu/it/
    - assets/svgs/game/

    - assets/jpgs/global/

    - assets/sounds/

    - assets/translations/
